M48
; DRILL file {KiCad 9.0.0} date 2025-03-19T10:55:41+1000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-19T10:55:41+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.780
%
G90
G05
T1
X107.95Y-66.04
X107.95Y-81.28
X148.59Y-66.04
X148.59Y-81.28
M30
