M48
; DRILL file {KiCad 9.0.0} date 2025-03-22T14:07:57+1000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-22T14:07:57+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.780
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X106.68Y-65.09
X106.68Y-80.33
X147.32Y-65.09
X147.32Y-80.33
T2
X94.54Y-63.59
X161.04Y-63.59
X164.04Y-100.59
M30
