M48
; DRILL file {KiCad 9.0.0} date 2025-03-22T14:08:41+1000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-22T14:08:41+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.780
%
G90
G05
T1
X106.68Y-65.09
X106.68Y-80.33
X147.32Y-65.09
X147.32Y-80.33
M30
